Fix: have CurrentLimits method in opev and oscev filter for LoadControlLimitDescription instead of MeasurementDescription
enbility/eebus-go pull request #144
Opened 2024-11-26 10:47 UTC by AhmedMagdyCoretech

Since the "ScopeType" field in the LoadControlLimitDescription is more relevant (with a value of "overloadProtection" and "selfConsumption" for OPEV and OSCEV, respectively), it shall be used as the filter for obtaining the relevant ElectricalConnectionPermittedValueSetListData items in the CurrentLimits getters for [OPEV](https://github.com/enbility/eebus-go/blob/59e7016a7018364d209f72331685b0ef0ba97b67/usecases/cem/opev/public.go#L19) and [OSCEV](https://github.com/enbility/eebus-go/blob/59e7016a7018364d209f72331685b0ef0ba97b67/usecases/cem/oscev/public.go#L19). From the relevant LoadControlLimitDescriptionData items, one can get their corresponding measurement IDs and use them to filter for relevant parameter description items.

2024-11-26 15:49 UTC, DerAndereAndi commented
Thank you @AhmedMagdyCoretech , this looks great!

2024-11-26 15:56 UTC, DerAndereAndi requested changes
Looks great overall, just some minor adjustments needed.

2024-11-26 15:56 UTC, DerAndereAndi commented on usecases/cem/opev/public.go
> +			MeasurementId: ld.MeasurementId,
This assumes `ld.MeasurementId` is never nil, but there are devices that provide loadControlLimits where all fields but the ID are empty.

We should check if all limits do provide a non nil `MeasurementId` and only then continue, otherwise return an error. This check could be added in line 50.

2024-11-26 15:56 UTC, DerAndereAndi commented on usecases/cem/opev/public.go
> +	if len(limitDescs) != 3 {
This check is not correct, as wallboxes could be connected with 1 Phase only. So we should only check for the array not to be empty.

2024-11-26 15:56 UTC, DerAndereAndi commented on usecases/cem/oscev/public.go
> +	if len(limitDescs) != 3 {
Same applies as in OPEV

2024-11-26 15:56 UTC, DerAndereAndi commented on usecases/cem/oscev/public.go
> +			MeasurementId: ld.MeasurementId,
Same applies as in OPEV

2024-11-26 22:23 UTC, AhmedMagdyCoretech commented
> Looks great overall, just some minor adjustments needed.

Thank you for the feedback. All the issues have been duly resolved.

2024-11-28 09:30 UTC, DerAndereAndi requested changes
I like the changes, just a minor last request regarding a variable name. Sorry if this looks picky, but I understand something else with `filters` .

2024-11-28 09:30 UTC, DerAndereAndi commented on usecases/cem/opev/public.go
> +		filter := model.MeasurementDescriptionDataType{
The variable name confuses me a bit. Maybe just use `measDesc` instead?

2024-11-28 09:30 UTC, DerAndereAndi commented on usecases/cem/oscev/public.go
> +		filter := model.MeasurementDescriptionDataType{
Same as in the other usecase

2024-11-28 09:55 UTC, AhmedMagdyCoretech commented
> I like the changes, just a minor last request regarding a variable name. Sorry if this looks picky, but I understand something else with `filters` .

Thank you for the feedback. Not so picky, I would say. Aptly addressed.

2024-11-28 09:56 UTC, DerAndereAndi approved these changes

2024-11-28 09:56 UTC, DerAndereAndi commented
Thank you very much @AhmedMagdyCoretech !

2024-11-28 09:57 UTC, merged